### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by odemolay** [jeanthom/TrinityEnabler#2]
looks like when we reboot we need to make the terminal setting again is it same for you ?

**Comment by jeanthom** [comment]
Yes that is perfectly normal. This utility sends settings to the DAC's RAM. This isn't permanent and should happen every time you plug your speakers. I could have done a kernel extension so that you wouldn't need to bother with this, but thank's to Apple's "security" policy, I'd need to have an Apple developer account ($$$) to sign my kext.

If your speakers are always connected to your Mac, I can suggest you to create a launchd service.
