### ISSUE TITLE
when power set to high, IOUSBDeviceInterface left with kIOUSBPipeStalled error

### ISSUE THREAD

**Issue by jhellerstein** [jeanthom/TrinityEnabler#3]
Thanks for this amazing resurrection of my speakers!

Things sound ok at 500mA on my CalDigit USB-C docking station, but better at 1500mA.  Unfortunately at the higher amperage the speakers occasionally cut out permanently if volume gets too high. 

If I try running trinityenabler again after that, it fails with "Error while disabling plugin." A bit of investigating with gdb shows that the DeviceRequest in xdfpSetMem returns with kIOUSBPipeStalled (79 .. see http://unix.superglobalmegacorp.com/xnu/newsrc/iokit/IOKit/usb/USB.h.html.)

Manually unplugging/replugging the USB cable clears the pipe, but it'd be nice if there was a programmatic way to do it -- was thinking it could reset, lower volume, and turn back on.

In any case, seems uncool to leave the pipe full -- should exit more gracefully.

**Comment by parrotgeek1** [comment]
Try in power1500mAEQSettings changing the -20000 to like -16000 (to be a little quieter but less power)

**Comment by jeanthom** [comment]
Hi @jhellerstein !

Thank you for your bug report :)

I guess your issue is related to how power management in the USB protocol works. When the USB enumeration process happens (basically when you plug a USB peripheral), the USB peripheral sends to the host its maximum current consumption.

The USB controller uses that value to limit the current the peripheral can draw. If the peripheral draws too much current, then the USB controller will shut down the USB port (hence the "kIOUSBPipeStalled" error, and you may get a notification from macOS telling you that a USB port has been shut down).

I guess that Trinity speakers declare a low current value (eg. 500mA) so that it can be used on normal USB ports on other Macs, and that on the PowerMac G4 Cube the USB ports don't have much current protection.

I never owned those speakers so I can't verify this hypothesis but if true there are three solutions :
* Build a USB cable with separate power & data, and connect the power connector to a 1.5A or 2A USB charger
* Find suitable macOS API that could override USB descriptors to allow more current consumption
* Tweak the DAC's firmware : it may or may not be technically possible, and if so, it would take a lot of time
